### ISSUE TITLE
Those two files should be removed from the git repo

### ISSUE THREAD

**Issue by asmwarrior** [perazz/wxMaterialDesignArtProvider#1]
[wxMaterialDesignIcons.depend](https://github.com/perazz/wxMaterialDesignArtProvider/blob/main/project/wxMaterialDesignIcons.depend)

This file is generated when building the project.

[wxMaterialDesignIcons.layout](https://github.com/perazz/wxMaterialDesignArtProvider/blob/main/project/wxMaterialDesignIcons.layout)

This file is remember the window layout of the Code::Blocks when you open the cbp.

Thanks.

**Comment by perazz** [comment]
Thank you @asmwarrior, closed by 69707a470d2d13d2a0b6a4efb05275bb0358ed61.
