### ISSUE TITLE
error compiling on Visual Studio 2022

### ISSUE THREAD

**Issue by ErikRomb** [perazz/wxMaterialDesignArtProvider#3]
Hello

Is this supported on Visual Studio?
When I try to compile with VS2022, I get a number of C2026 errors on wxSimpleIconsArt.hpp, e.g.

1>C:\dev\wxMaterialDesignArtProvider\MaterialDesign\wxSimpleIconsArt.hpp(3615,1): error C2026: string too big, trailing characters truncated

indicating that string literals are too long.

Kind regards

**Comment by perazz** [comment]
Thanks for checking @ErikRomb. I don't have a MSVC solution handy but #4 should do the job.
